21:37:36 play.Logger INFO : Starting D:\workspace\immunology-play
21:38:18 play.Logger INFO : Starting D:\workspace\immunology-play
21:38:19 play.Logger WARN : You're running Play! in DEV mode
21:38:19 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
21:38:42 play.Logger ERROR: Cannot include routes for module secure (not found)
21:38:42 play.Logger ERROR: Cannot include routes for module crud (not found)
21:38:45 play.Logger ERROR: 

@6db83hdod
Internal Server Error (500) for request GET /

Compilation error (In /app/controllers/Allergens.java around line 7)
The file /app/controllers/Allergens.java could not be compiled. Error raised is : CRUD cannot be resolved to a type

play.exceptions.CompilationException: CRUD cannot be resolved to a type
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:424)
	at play.Play.start(Play.java:505)
	at play.Play.detectChanges(Play.java:618)
	at play.Invoker$Invocation.init(Invoker.java:198)
	at Invocation.HTTP Request(Play!)
21:38:46 play.Logger ERROR: 

@6db83hdoh
Internal Server Error (500) for request GET /favicon.ico

Compilation error (In /app/controllers/AnamnesisDetails.java around line 7)
The file /app/controllers/AnamnesisDetails.java could not be compiled. Error raised is : CRUD cannot be resolved to a type

play.exceptions.CompilationException: CRUD cannot be resolved to a type
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:277)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:322)
	at play.Play.detectChanges(Play.java:614)
	at play.Invoker$Invocation.init(Invoker.java:198)
	at Invocation.HTTP Request(Play!)
21:42:32 play.Logger INFO : Starting D:\workspace\immunology-play
21:42:32 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
21:42:32 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
21:42:32 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
21:42:33 play.Logger WARN : You're running Play! in DEV mode
21:42:33 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
21:42:51 play.Logger INFO : Connected to jdbc:postgresql://localhost:5432/Immunology
21:42:54 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add column clinicalManifestationComplaint_clinical_manifestation_complaint_id int8
21:42:54 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: колонка "clinicalmanifestationcomplaint_clinical_manifestation_complaint" отношения "clinical_manifestation" уже существует
21:42:54 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add constraint FKFD048DFA35D8A6E9 foreign key (clinicalManifestationComplaint_clinical_manifestation_complaint_id) references clinical_manifestation_complaint
21:42:54 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: ограничение "fkfd048dfa35d8a6e9" для отношения "clinical_manifestation" уже существует
21:42:55 play.Logger INFO : Application 'immunology' is now started !
21:43:11 controllers.Application INFO : loggedUser:Лікар: User Лікар Лікар; isAdmin: false
21:43:11 controllers.PatientView INFO : patients(2)
21:43:11 play.Logger INFO : getPatientsByUserId(2)
21:43:11 play.Logger INFO : getPatientsByUserId result: []
21:43:20 controllers.PatientView INFO : updatePatientsTable(ALL)
21:43:22 controllers.PatientView INFO : adding new user
21:43:43 controllers.PatientView INFO : savePatientWithCard([test test test])
21:43:48 controllers.PatientView INFO : savePatientWithCard([test test test])
21:43:48 controllers.PatientView INFO : show(1)
21:44:10 controllers.PatientView INFO : patients(2)
21:44:10 play.Logger INFO : getPatientsByUserId(2)
21:44:10 play.Logger INFO : getPatientsByUserId result: []
21:44:13 controllers.PatientView INFO : updatePatientsTable(ALL)
21:44:16 controllers.PatientView INFO : show(1)
21:44:21 play.Logger ERROR: 

@6db847apb
Internal Server Error (500) for request POST /chartController/getInsufficiencyDegreeData

Execution exception (In /app/controllers/ChartController.java around line 45)
StringIndexOutOfBoundsException occured : String index out of range: -1

play.exceptions.JavaExecutionException: String index out of range: -1
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:789)
	at java.lang.StringBuilder.replace(StringBuilder.java:266)
	at controllers.ChartController.getInsufficiencyDegreeData(ChartController.java:45)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
21:44:23 play.Logger ERROR: 

@6db847apc
Internal Server Error (500) for request POST /chartController/getDifficultyDegreeData

Execution exception (In /app/controllers/ChartController.java around line 28)
StringIndexOutOfBoundsException occured : String index out of range: -1

play.exceptions.JavaExecutionException: String index out of range: -1
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:789)
	at java.lang.StringBuilder.replace(StringBuilder.java:266)
	at controllers.ChartController.getDifficultyDegreeData(ChartController.java:28)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
21:44:47 controllers.Application INFO : loggedUser:Адміністратор: Адмін Адмін Адмін; isAdmin: true
22:02:06 play.Logger INFO : Starting D:\workspace\immunology-play
22:02:06 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
22:02:06 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
22:02:06 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
22:02:06 play.Logger WARN : You're running Play! in DEV mode
22:02:06 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
22:02:10 play.Logger WARN : Locale uk is not defined in your application.conf
22:02:13 play.Logger INFO : Connected to jdbc:postgresql://localhost:5432/Immunology
22:02:15 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add column clinicalManifestationComplaint_clinical_manifestation_complaint_id int8
22:02:15 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: колонка "clinicalmanifestationcomplaint_clinical_manifestation_complaint" отношения "clinical_manifestation" уже существует
22:02:15 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add constraint FKFD048DFA35D8A6E9 foreign key (clinicalManifestationComplaint_clinical_manifestation_complaint_id) references clinical_manifestation_complaint
22:02:15 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: ограничение "fkfd048dfa35d8a6e9" для отношения "clinical_manifestation" уже существует
22:02:15 play.Logger INFO : Application 'immunology' is now started !
15:42:01 play.Logger INFO : Starting D:\workspace\immunology-play
15:42:01 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
15:42:01 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
15:42:01 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
15:42:03 play.Logger WARN : You're running Play! in DEV mode
15:42:03 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
19:07:07 play.Logger INFO : Starting D:\workspace\immunology-play
19:07:07 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
19:07:07 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
19:07:07 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
19:07:09 play.Logger WARN : You're running Play! in DEV mode
19:07:10 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
19:07:30 play.Logger INFO : Connected to jdbc:postgresql://localhost:5432/Immunology
19:07:37 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add column clinicalManifestationComplaint_clinical_manifestation_complaint_id int8
19:07:37 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: колонка "clinicalmanifestationcomplaint_clinical_manifestation_complaint" отношения "clinical_manifestation" уже существует
19:07:37 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add constraint FKFD048DFA35D8A6E9 foreign key (clinicalManifestationComplaint_clinical_manifestation_complaint_id) references clinical_manifestation_complaint
19:07:37 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: ограничение "fkfd048dfa35d8a6e9" для отношения "clinical_manifestation" уже существует
19:07:38 play.Logger INFO : Application 'immunology' is now started !
19:07:51 controllers.Application INFO : loggedUser:Адміністратор: Адмін Адмін Адмін; isAdmin: true
19:08:13 controllers.Application INFO : loggedUser:Адміністратор: Адмін Адмін Адмін; isAdmin: true
19:10:14 controllers.Application INFO : loggedUser:Лікар: User Лікар Лікар; isAdmin: false
19:10:14 controllers.PatientView INFO : patients(2)
19:10:14 play.Logger INFO : getPatientsByUserId(2)
19:10:14 play.Logger INFO : getPatientsByUserId result: []
19:18:59 controllers.PatientView INFO : adding new user
19:19:17 controllers.PatientView INFO : savePatientWithCard([rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj])
19:19:23 controllers.PatientView INFO : savePatientWithCard([rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj])
19:19:24 controllers.PatientView INFO : show(2)
19:28:28 controllers.PatientView INFO : patients(2)
19:28:28 play.Logger INFO : getPatientsByUserId(2)
19:28:28 play.Logger INFO : getPatientsByUserId result: []
19:28:33 controllers.PatientView INFO : updatePatientsTable(ALL)
19:28:37 controllers.PatientView INFO : show(1)
19:33:12 controllers.Application INFO : loggedUser:Лікар: User Лікар Лікар; isAdmin: false
19:33:12 controllers.PatientView INFO : patients(2)
19:33:12 play.Logger INFO : getPatientsByUserId(2)
19:33:12 play.Logger INFO : getPatientsByUserId result: []
19:33:15 controllers.PatientView INFO : updatePatientsTable(ALL)
19:33:18 controllers.PatientView INFO : show(1)
19:33:22 play.Logger ERROR: 

@6dennjloe
Internal Server Error (500) for request POST /chartController/getDifficultyDegreeData

Execution exception (In /app/controllers/ChartController.java around line 28)
StringIndexOutOfBoundsException occured : String index out of range: -1

play.exceptions.JavaExecutionException: String index out of range: -1
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:789)
	at java.lang.StringBuilder.replace(StringBuilder.java:266)
	at controllers.ChartController.getDifficultyDegreeData(ChartController.java:28)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
19:33:24 play.Logger ERROR: 

@6dennjlof
Internal Server Error (500) for request POST /chartController/getInsufficiencyDegreeData

Execution exception (In /app/controllers/ChartController.java around line 45)
StringIndexOutOfBoundsException occured : String index out of range: -1

play.exceptions.JavaExecutionException: String index out of range: -1
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:789)
	at java.lang.StringBuilder.replace(StringBuilder.java:266)
	at controllers.ChartController.getInsufficiencyDegreeData(ChartController.java:45)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
19:34:43 play.Logger ERROR: 

@6dennjlog
Internal Server Error (500) for request POST /chartController/getDifficultyDegreeData

Execution exception (In /app/controllers/ChartController.java around line 28)
StringIndexOutOfBoundsException occured : String index out of range: -1

play.exceptions.JavaExecutionException: String index out of range: -1
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:789)
	at java.lang.StringBuilder.replace(StringBuilder.java:266)
	at controllers.ChartController.getDifficultyDegreeData(ChartController.java:28)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
19:43:03 controllers.Application INFO : loggedUser:Адміністратор: Адмін Адмін Адмін; isAdmin: true
19:44:21 util.JDBCExceptionReporter WARN : SQL Error: 0, SQLState: 23502
19:44:21 util.JDBCExceptionReporter ERROR: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '413', '234', '42', '21', '412', '1', NULL, '2013-02-27 00:00:00.000000 +02:00:00', NULL, NULL, '1') was aborted.  Call getNextException to see the cause.
19:44:21 util.JDBCExceptionReporter WARN : SQL Error: 0, SQLState: 23502
19:44:21 util.JDBCExceptionReporter ERROR: ОШИБКА: нулевое значение в колонке "syndrome_syndrome_id" нарушает ограничение NOT NULL
19:44:21 def.AbstractFlushingEventListener ERROR: Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:345)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:795)
	at play.db.jpa.JPABase._save(JPABase.java:35)
	at controllers.CRUD.create(CRUD.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:257)
	at play.Invoker$Invocation.run(Invoker.java:278)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '413', '234', '42', '21', '412', '1', NULL, '2013-02-27 00:00:00.000000 +02:00:00', NULL, NULL, '1') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 28 more
19:44:21 play.Logger ERROR: 

@6dennjm5m
Internal Server Error (500) for request POST /objects/surveys

Execution exception (In {module:crud}/app/controllers/CRUD.java around line 152)
PersistenceException occured : org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update

play.exceptions.JavaExecutionException: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1214)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1147)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1153)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:798)
	at play.db.jpa.JPABase._save(JPABase.java:35)
	at controllers.CRUD.create(CRUD.java:152)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
Caused by: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:345)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:795)
	... 8 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '413', '234', '42', '21', '412', '1', NULL, '2013-02-27 00:00:00.000000 +02:00:00', NULL, NULL, '1') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 14 more
19:44:47 util.JDBCExceptionReporter WARN : SQL Error: 0, SQLState: 23502
19:44:47 util.JDBCExceptionReporter ERROR: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '3', '2', '4', '5', '3', '1', NULL, '2013-02-22 00:00:00.000000 +02:00:00', NULL, NULL, '2') was aborted.  Call getNextException to see the cause.
19:44:47 util.JDBCExceptionReporter WARN : SQL Error: 0, SQLState: 23502
19:44:47 util.JDBCExceptionReporter ERROR: ОШИБКА: нулевое значение в колонке "syndrome_syndrome_id" нарушает ограничение NOT NULL
19:44:47 def.AbstractFlushingEventListener ERROR: Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:345)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:795)
	at play.db.jpa.JPABase._save(JPABase.java:35)
	at controllers.CRUD.create(CRUD.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:257)
	at play.Invoker$Invocation.run(Invoker.java:278)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '3', '2', '4', '5', '3', '1', NULL, '2013-02-22 00:00:00.000000 +02:00:00', NULL, NULL, '2') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 28 more
19:44:47 play.Logger ERROR: 

@6dennjm5o
Internal Server Error (500) for request POST /objects/surveys

Execution exception (In {module:crud}/app/controllers/CRUD.java around line 152)
PersistenceException occured : org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update

play.exceptions.JavaExecutionException: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
	at Invocation.HTTP Request(Play!)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1214)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1147)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1153)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:798)
	at play.db.jpa.JPABase._save(JPABase.java:35)
	at controllers.CRUD.create(CRUD.java:152)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
Caused by: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:345)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:795)
	... 8 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into survey (alergetic_difficulty_degree, alergetic_insufficiency_degree, autoimmuno_difficulty_degree, autoimmuno_insufficiency_degree, immunodef_difficulty_degree, immunodef_insufficiency_degree, medicineCard_medicine_card_id, nosology_nosology_id, date, syndrome_syndrome_id, user_user_id, survey_id) values ('2', '3', '2', '4', '5', '3', '1', NULL, '2013-02-22 00:00:00.000000 +02:00:00', NULL, NULL, '2') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2598)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 14 more
18:30:48 play.Logger INFO : Starting D:\workspace\immunology-play
18:30:48 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
18:30:48 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
18:30:48 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
18:30:51 play.Logger WARN : You're running Play! in DEV mode
18:30:53 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
18:31:15 play.Logger INFO : Connected to jdbc:postgresql://localhost:5432/Immunology
18:31:23 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add column clinicalManifestationComplaint_clinical_manifestation_complaint_id int8
18:31:23 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: колонка "clinicalmanifestationcomplaint_clinical_manifestation_complaint" отношения "clinical_manifestation" уже существует
18:31:23 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add constraint FKFD048DFA35D8A6E9 foreign key (clinicalManifestationComplaint_clinical_manifestation_complaint_id) references clinical_manifestation_complaint
18:31:23 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: ограничение "fkfd048dfa35d8a6e9" для отношения "clinical_manifestation" уже существует
18:31:23 play.Logger INFO : Application 'immunology' is now started !
18:31:37 controllers.Application INFO : loggedUser:Адміністратор: Адмін Адмін Адмін; isAdmin: true
18:37:39 controllers.Application INFO : loggedUser:Лікар: User Лікар Лікар; isAdmin: false
18:37:39 controllers.PatientView INFO : patients(2)
18:37:39 play.Logger INFO : getPatientsByUserId(2)
18:37:40 play.Logger INFO : getPatientsByUserId result: [[rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj]]
18:37:47 controllers.PatientView INFO : show(2)
18:38:30 controllers.PatientView INFO : updatePatientsTable(ALL)
18:38:34 controllers.PatientView INFO : updatePatientsTable(USERS)
18:38:34 play.Logger INFO : getPatientsByUserId(2)
18:38:34 play.Logger INFO : getPatientsByUserId result: [[rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj]]
18:38:35 controllers.PatientView INFO : updatePatientsTable(ALL)
20:34:20 play.Logger INFO : Starting D:\workspace\immunology-play
20:34:20 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
20:34:20 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
20:34:20 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
20:34:22 play.Logger WARN : You're running Play! in DEV mode
20:34:22 play.Logger INFO : Listening for HTTP on port 9000 (Waiting a first request to start) ...
20:34:32 play.Logger INFO : Connected to jdbc:postgresql://localhost:5432/Immunology
20:34:37 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add column clinicalManifestationComplaint_clinical_manifestation_complaint_id int8
20:34:37 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: колонка "clinicalmanifestationcomplaint_clinical_manifestation_complaint" отношения "clinical_manifestation" уже существует
20:34:37 hbm2ddl.SchemaUpdate ERROR: Unsuccessful: alter table clinical_manifestation add constraint FKFD048DFA35D8A6E9 foreign key (clinicalManifestationComplaint_clinical_manifestation_complaint_id) references clinical_manifestation_complaint
20:34:37 hbm2ddl.SchemaUpdate ERROR: ОШИБКА: ограничение "fkfd048dfa35d8a6e9" для отношения "clinical_manifestation" уже существует
20:34:38 play.Logger INFO : Application 'immunology' is now started !
20:34:51 controllers.Application INFO : loggedUser:Лікар: User Лікар Лікар; isAdmin: false
20:34:51 controllers.PatientView INFO : patients(2)
20:34:51 play.Logger INFO : getPatientsByUserId(2)
20:34:51 play.Logger INFO : getPatientsByUserId result: [[rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj]]
20:34:56 controllers.PatientView INFO : adding new user
20:34:58 controllers.PatientView INFO : patients(2)
20:34:58 play.Logger INFO : getPatientsByUserId(2)
20:34:58 play.Logger INFO : getPatientsByUserId result: [[rghdfjkg fkjsghdjhgjk jkfsgjhskdghkj]]
20:35:00 controllers.PatientView INFO : show(2)
20:35:58 controllers.PatientView INFO : show(2)
20:51:10 controllers.PatientView INFO : show(2)
20:51:13 controllers.PatientView INFO : show(2)
20:52:14 controllers.PatientView INFO : show(2)
20:52:48 controllers.PatientView INFO : show(2)
20:54:23 controllers.PatientView INFO : show(2)
20:55:29 controllers.PatientView INFO : show(2)
23:05:11 play.Logger INFO : Starting D:\workspace\immunology-play
23:05:11 play.Logger INFO : Module crud is available (d:\JAVA\play-1.2.4\modules\crud)
23:05:11 play.Logger INFO : Module jqueryui is available (D:\workspace\immunology-play\modules\jqueryui-1.0)
23:05:11 play.Logger INFO : Module secure is available (d:\JAVA\play-1.2.4\modules\secure)
23:05:13 play.Logger INFO : Precompiling ...
23:05:34 play.Logger INFO : Done.
